### ISSUE TITLE
Any documentation on how to use it?

### ISSUE THREAD

**Issue by emtiazahmed** [mcspronko/grav-plugin-newsletter#1]
Hi Max,

I am very interested in using your plugin. Do you have any documentation or instructions on how to use it and customize it?

**Comment by Fauphi** [comment]
Copy the content of this repo in /user/plugins/newsletter, then goto /user/data and create a folder named "newsletter" and in that new folder create a folder named "subscribers". After that you will see a tab called "Newsletter" in the admin panel.

Thats how far I got, but still have no idea how to display the newsletter form on a client page...

**Comment by mcspronko** [comment]
Hi @emtiazahmed and @Fauphi,

Where are you now with newsletter plugin?
What is your expectation for the functionality?

Thanks,
Max

**Comment by bashou** [comment]
Hi @mcspronko,

Maybe you can write a README to explain how to install this plugin (it's ok for me) and how we can use it (it's not ok for me) ?

Thanks !

**Comment by zeigerpuppy** [comment]
I can't get any options for it to appear by following the instructions here.
I also agree, this plugin needs some install instructions

**Comment by mcspronko** [comment]
Hi @bashou @zeigerpuppy @emtiazahmed @Fauphi 

Added example for form configuration on a page.

**Comment by zeigerpuppy** [comment]
Thanks.  This looks really useful.  I'm wondering how it works in a little more detail however.
It looks like the form allows signing up and creating a list of "subscribed" people.  
I don't think I see functionality for creating the newsletters themselves.

It would be great if it was possible to then create pages that are newsletters.  That is, if I created page: `user/pages/newsletter/2016-12-21-first-newsletter/newsletter.md`
It would be sent via email to the subscribed people.  I guess this could be done with a daily cron job.

**Comment by mcspronko** [comment]
@zeigerpuppy there is no functionality to send a newsletter. This is something I am going to work on.

Thanks for the suggestion about newsletter as a page, really great idea, I will create a separate issue for tracking.
