### ISSUE TITLE
Autoloading issue

### ISSUE THREAD

**Issue by sherpadawan** [mcspronko/grav-plugin-newsletter#3]
Any fix for the autoloading issue ? I haven't wrked with php for a while, so I need a help to fix this. I'd to contribute to your plugin after that. Thanks in advance. https://github.com/mcspronko/grav-plugin-newsletter/blob/70a6104015b4cc0a4bcac0dc46b4a00a55ec6356/newsletter.php#L41

**Comment by mcspronko** [comment]
Thank you for your question @sherpadawan. I see that there is a temporary fix provided by @sherpadawan which could work. But we need to get an update for the whole plugin to ensure it works with the latest Grav as I didn't have a time to look it for a while. Are you interested?

**Comment by mcspronko** [comment]
Fixed the autoloading, now it is fine.
