### ISSUE TITLE
Path user/data/newsletter/subscribers must be created on plugin install

### ISSUE THREAD

**Issue by sherpadawan** [mcspronko/grav-plugin-newsletter#4]
According to this 
https://github.com/mcspronko/grav-plugin-newsletter/blob/70a6104015b4cc0a4bcac0dc46b4a00a55ec6356/classes/newsletter.php#L28

Path user/data/newsletter/subscribers must be created on plugin install

**Comment by mcspronko** [comment]
@sherpadawan agree with you on that. I will work on it or if you can submit a PR. Let me know. Thanks.

**Comment by sherpadawan** [comment]
I really want to continue helping to develop your plugin. I need time and to learn more about grave api and Plugin dev, the doc is shallow. Nice to see you are still alive 

Le 10 juillet 2019 21:25:55 CEST, Max Pronko <notifications@github.com> a écrit :
>@sherpadawan agree with you on that. I will work on it or if you can
>submit a PR. Let me know. Thanks.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mcspronko/grav-plugin-newsletter/issues/4#issuecomment-510195314

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by mcspronko** [comment]
I am adding the onPluginsInitialized event to create a directory if it doesn't exist.

**Comment by mcspronko** [comment]
Implemented here https://github.com/mcspronko/grav-plugin-newsletter/commit/b9b19e1974e93d820acf231587885ea663d11194

Let me know if you have questions.
